.TH "ctys-vmw2utils" 1 "June, 2010" ""

.P
\&.

.SH NAME
.P
\fBctys-vmw2utils - VMW-Server2 utilities\fR

.SH SYNTAX
.P
\fBctys-vmw2utils\fR 

   [-d <debug-options>]
   [-h]
   [-H <help-options>]
   [-n]
   [-V]
   [-X]
   [
     (
       (FETCH|F) (
           VMWPATH4OBJID|P4O
          |VMWOBJID4PATH|O4P
          |DATASTORE|D
        )
     )
     |
     (
       (CONVERT|C) (TODATASTORE|2D)
     )
     |
     (
       (LIST|L) (
           INVENTORY|I
          |DATASTORES|D
       )
     )
   ]


.SH DESCRIPTION
.P
\fBctys\-vmw2utils\fR is a collection of function calls for display and conversion 
of Inventory data form VMWare Server 2.x(TM).
The call could be executed on localhost or on a remote host with the tool 'ctys\-beamer'.

.P
\&.

.SH OPTIONS
.P
\fBctys-vmw2utils\fR 

.SS -d <debug-args>
.P
Refer to "ctys" generic options for additional information.

.SS -h
.P
Print help, refer to "\-H" for additional information.

.SS -H <help-option>
.P
The extended help option is based on system interfaces for display of
manpages, PDF  and HTML documents.
This comprises the man pages and installed manuals.

.P
For additional help refer to the documents or type \fBctys \-H help\fR.

.SS -V
.P
Version.

.SS -X
.P
Terse output format, effects "\-V" when set left\-of.

.P
\&.

.SH ARGUMENTS
.TP
\fB<command>\fR
The commands to be executed on the localhost or remote machine.

.TP
\fBCONVERT <subargs>\fR
.TP

\fBTODATASTORE <pathname>\fR
Converts a pathname to a datastore.

.TP
\fBFETCH <subargs>\fR
.RS
.IP \(bu 3
\fBVMWPATH4OBJID <OID>\fR
Transforms the provided object ID to a pathname.

.IP \(bu 3
\fBVMWOBJID4PATH <pathname>\fR
Transforms the provided pathname to an object ID.

.IP \(bu 3
\fBDATASTORE <pathname>\fR
Displays the datastore for a given pathname.
.RE

.TP
\fBLIST <subargs>\fR
Lists the requested entries.

.RS
.IP \(bu 3
\fBINVENTORY\fR
Lists the contents of the inventory as defined by the variable:

.nf
  VMW_INVENTORY_DEFAULT=\e
  ${VMW_INVENTORY_DEFAULT:-/etc/vmware/hostd/vmInventory.xml}
.fi


.IP \(bu 3
\fBDATASTORES\fR
Lists the present datastores.

.nf
  VMW_DATASTORE_DEFAULT=\e
  ${VMW_DATASTORE_DEFAULT:-/etc/vmware/hostd/datastores.xml}
.fi

.RE

.P
\&.

.SH EXIT-VALUES
.TP
 0: OK:
Result is valid.

.TP
 1: NOK:
Erroneous parameters.

.TP
 2: NOK:
Missing an environment element like files or databases.

.SH SEE ALSO
.TP
  \fBVMs\fR
\fIctys\-VMV(7)\fR

.SH AUTHOR
.TS
tab(^); ll.
 Maintenance:^<acue_sf1@users.sourceforge.net>
 Homepage:^<http://www.UnifiedSessionsManager.org>
 Sourceforge.net:^<http://sourceforge.net/projects/ctys>
 Berlios.de:^<http://ctys.berlios.de>
 Commercial:^<http://www.i4p.com>
.TE


.SH COPYRIGHT
.P
Copyright (C) 2008, 2009, 2010, 2011 Ingenieurbuero Arno\-Can Uestuensoez

.P
This is software and documentation from \fBBASE\fR package,

.RS
.IP \(bu 3
for software see GPL3 for license conditions,
.IP \(bu 3
for documents  see GFDL\-1.3 with invariant sections for license conditions.

The whole document \- all sections \- is/are defined as invariant.
.RE

.P
For additional information refer to enclosed Releasenotes and License files.


.\" man code generated by txt2tags 2.3 (http://txt2tags.sf.net)
.\" cmdline: txt2tags -t man -i ctys-vmw2utils.t2t -o /tmpn/0/ctys/bld/01.11.022/doc-tmp/BASE/en/man/man1/ctys-vmw2utils.1

