#!/bin/bash

########################################################################
#
#PROJECT:      Unified Sessions Manager
#AUTHOR:       Arno-Can Uestuensoez - acue@UnifiedSessionsManager.org
#MAINTAINER:   Arno-Can Uestuensoez - acue_sf1@sourceforge.net
#SHORT:        ctys
#CALLFULLNAME: Commutate To Your Session
#LICENCE:      GPL3
#VERSION:      01_02_007a17
#
########################################################################
#
# Copyright (C) 2007 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
#
########################################################################

_myPKGNAME_PM_LIST="${BASH_SOURCE}"
_myPKGVERS_PM_LIST="01.00.001a00"
hookInfoAdd $_myPKGNAME_PM_LIST $_myPKGVERS_PM_LIST



#FUNCBEG###############################################################
#NAME:
#  listMySessionsPM
#
#TYPE:
#  bash-function
#
#DESCRIPTION:
#  Lists all PM sessions.
#
#EXAMPLE:
#
#PARAMETERS:
# $1: C|S|B
#     determines the filter to be applied.
#     C: clients
#     S: servers
#     B: both
#
#OUTPUT:
#  RETURN:
#
#  VALUES:
#
#FUNCEND###############################################################
function listMySessionsPM () {
    local _site=$1;shift

    printDBG $S_PM ${D_BULK} $LINENO $BASH_SOURCE "${FUNCNAME}:\$@=$@"

    case ${MYOS} in
	OpenBSD);;
	Linux);;
	SunOS);;
	*)
	    printDBG $S_PM ${D_FLOW} $LINENO $BASH_SOURCE "${FUNCNAME}:OS not supported by PM:${MYOS}"
	    return
    esac
    if [ "${_site}" != S -a "${_site}" != B ];then
	return
    fi

    printDBG $S_PM ${D_BULK} $LINENO $BASH_SOURCE "$FUNCNAME $_site <$*>"
    if [ "${C_SESSIONTYPE}" != "PM" -a "${C_SESSIONTYPE}" != "ALL" ];then 
        ABORT=2
        printERR $LINENO $BASH_SOURCE ${ABORT} "Unexpected session type:C_SESSIONTYPE=${C_SESSIONTYPE}"
        gotoHell ${ABORT}
    fi

    local X=/etc/ctys.d/pm.conf
    if [ ! -f "${X}" ];then
	local X=/etc/ctys.d/vm.conf
    fi
    local _out=;

    local _out1=;
    _out1="${MYHOST}"; 
    _out1="${_out1};`getLABEL ${X}`";
    _out1="${_out1};${X}";
    _out1="${_out1};`getUUID ${X}`";
    #out="${_out};`getMAC ${X}`";
    local _out2=;
    _out2="${_out2};";
    _out2="${_out2};";
    _out2="${_out2};";
    _out2="${_out2};1";
    _out2="${_out2};`getUID ${X}`";
    _out2="${_out2};`getGID ${X}`";
#    _out2="${_out2};PM";
    _out2="${_out2};`getCATEGORY ${X}`";
    _out2="${_out2};SERVER";

    local _cnt=0;
    local _il="`netGetIFlst`";
    printDBG $S_PM ${D_FLOW} $LINENO $BASH_SOURCE "${FUNCNAME}:Polled if-list:${_il}"
    for i in $_il;do
	_out="${_out1};${i%%=*}${_out2};${i##*=}";
	_out="${_out};";
	echo $_out
        let _cnt++;
    done
    if((_cnt==0));then
	_out="${_out1};${_out2};";
	_out="${_out};";
	echo $_out
    fi
}
