#!/bin/bash

########################################################################
#
#PROJECT:      Unified Sessions Manager
#AUTHOR:       Arno-Can Uestuensoez - acue@UnifiedSessionsManager.org
#MAINTAINER:   Arno-Can Uestuensoez - acue_sf1@sourceforge.net
#SHORT:        ctys
#CALLFULLNAME: Commutate To Your Session
#LICENCE:      GPL3
#VERSION:      01_02_007a17
#
########################################################################
#
# Copyright (C) 2007 Arno-Can Uestuensoez (UnifiedSessionsManager.org)
#
########################################################################

_myPKGNAME_CLI_SESSION="${BASH_SOURCE}"
_myPKGVERS_CLI_SESSION="01.01.001a01"
hookInfoAdd $_myPKGNAME_CLI_SESSION $_myPKGVERS_CLI_SESSION
_myPKGBASE_CLI_SESSION="`dirname ${_myPKGNAME_CLI_SESSION}`"

_CLI_SESSION="${_myPKGNAME_CLI_SESSION}"




#FUNCBEG###############################################################
#NAME:
#  startSessionCLI
#
#TYPE:
#  bash-function
#
#DESCRIPTION:
#
#EXAMPLE:
#
#PARAMETERS:
#  $1:  <label>
#  $2:  <callopts>
#  $3:  <xopts>
#
#OUTPUT:
#  RETURN:
#
#  VALUES:
#
#FUNCEND###############################################################
function startSessionCLI () {
    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:\$@=$@"
    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:\$1=$1"
    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:\$2=$2"
    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:\$3=$3"
    local _label=${1:-DEFAULT-$DATETIME};shift
    checkUniqueness4Label ${_label};
    if [ $? -eq 0 ];then
	local _unique=1
    else
	if [ -z "${CTRL_ALLOWAMBIGIOUS}" ];then
	    ABORT=2
	    printERR $LINENO $BASH_SOURCE ${ABORT} "${FUNCNAME}:Ambigious <session-label>:${_label}"
	    gotoHell ${ABORT}
	else 
	    printWNG $LINENO $BASH_SOURCE ${RET} "${FUNCNAME}:Label is ambigious:${_label}"
	fi
    fi

    _label2="${USER}@${MYHOST}:${_label}"
    case "${2}" in 
        bash*)
            echo -ne "\033]2;${_label2}\007\033]1;\007"
	    ;;
	*)
	    local _title=" --title ${_label2} "
	    ;;
    esac 

#    BATCHTASK=":CLI:chost:${_label}:${MYHOST}"
    local _execStrg="$*  ${_title}"

    printVerboseDebug ${DBG_LVL_MAINT} $LINENO $BASH_SOURCE "$FUNCNAME:_execStrg=${_execStrg}"
    [ -z "${CTRL_NOEXEC}" ]&&${_execStrg}
}


